---
tags: [caching, cache]
projects: [spring-framework]
---
:spring_version: current
:spring_boot_version: 1.0.2.RELEASE
:SpringData: http://projects.spring.io/spring-data/
:Cacheable: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/cache/annotation/Cacheable.html
:CachePut: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/cache/annotation/CachePut.html
:CacheEvict: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/cache/annotation/CacheEvict.html
:CachingConfigurer: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/cache/annotation/CachingConfigurer.html
:EnableCaching: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/cache/annotation/EnableCaching.html
:CacheManager: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/cache/CacheManager.html
:documentation: http://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: draft-gs-caching
This guide walks you through the process of enabling caching on a Spring managed bean.

== What you'll build

You'll build an application that enables caching on a simple book repository.


== What you'll need

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


[[scratch]]
== Set up the project

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_system_intro.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/create_directory_structure_hello.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/create_both_builds.adoc[]

`build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::initial/build.gradle[]
----

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-gradle-plugin.adoc[]


[[initial]]
== Create a book repository

First, let's create a very simple model for our book

`src/main/java/hello/Book.java`
[source,java]
----
include::initial/src/main/java/hello/Book.java[]
----

And a repository for that model:

`src/main/java/hello/BookRepository.java`
[source,java]
----
include::initial/src/main/java/hello/BookRepository.java[]
----

We could have used {SpringData}[Spring Data] to provide an implementation of our
repository over a wide range of SQL or NoSQL stores but for the purpose of this
guide, we will simply use a naive implementation that simulates some latency
(network service, slow delay, etc).

`src/main/java/hello/SimpleBookRepository.java`
[source,java]
----
include::initial/src/main/java/hello/SimpleBookRepository.java[]
----

== Using the repository
Next, wire up the repository and use it to access some books. If you try to run the
application at this point, you'll notice it's quite slow even though we are retrieving
the exact same book several times.

`src/main/java/hello/Application.java`
[source,java]
----
include::initial/src/main/java/hello/Application.java[]
----

== Enable caching

Let's enable caching on our `SimpleBookRepository` so that the books are cached within
the `books` cache.

`src/main/java/hello/SimpleBookRepository.java`
[source,java]
----
include::complete/src/main/java/hello/SimpleBookRepository.java[]
----

We now need to enable the processing of the caching annotations

`src/main/java/hello/Application.java`
[source,java]
----
include::complete/src/main/java/hello/Application.java[]
----

The {EnableCaching}[`@EnableCaching`] annotation triggers a post processor that
inspects every Spring bean for the presence of caching annotations on public
methods. If such annotation is found, a proxy is created automatically to intercept
the method call and handle the cache accordingly.

The annotations that are managed by this post processor are {Cacheable}[`Cacheable`],
{CachePut}[`CachePut`] and {CacheEvict}[`CacheEvict`], refer to the javadoc and
{documentation}[the documentation] for more details.

In its most basic setup, the annotation requires a {CacheManager}[`CacheManager`] to
serve as a provider for the relevant cache. In our example we use an implementation
that delegates to a `ConcurrentHashMap`. The {CachingConfigurer}[`CachingConfigurer`]
interface provides more advanced configuration options.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_subhead.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]

:module: service
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/run_the_application_with_both.adoc[]


== Test the application

Now that caching is enabled, you can execute it again and see the difference by adding additional
calls with or without the same isbn.


== Summary

Congratulations! You've just enabled caching to a Spring managed bean.



