---
tags: [jdbc, spring-boot]
projects: [spring-framework, spring-boot]
---
:spring_version: current
:spring_boot_version: 1.1.6.RELEASE
:Component: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/stereotype/Component.html
:Controller: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/stereotype/Controller.html
:DispatcherServlet: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/servlet/DispatcherServlet.html
:SpringApplication: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/SpringApplication.html
:ResponseBody: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/bind/annotation/ResponseBody.html
:EnableAutoConfiguration: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/autoconfigure/EnableAutoConfiguration.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: draft-gs-spring-boot-jdbc
This guide walks you through the process of creating a Spring application.

== What you'll build

You'll build a Spring Boot application that uses JdbcTemplate to access an in-memory relational database.


== What you'll need

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]

Also create the following subdirectory structure; for example, with `mkdir -p src/main/resources` on *nix systems:

....
└── src
        └── main
            └── resources
....

[[initial]]

== Setup the data
Spring Boot will automatically configure an embedded in-memory database and enable the Spring JDBC DataSource initializer feature by default.  It will load the `schema-${platform}.sql` and `data-${platform}.sql` files where platform is the spring.datasource.platform value defined in the `application.properties` file.

To configure the spring.datasource.platform property, cd to the `src/main/resources` directory and create an `application.properties` file. Set the spring.datasource.platform to hsqldb.

`src/main/resources/application.properties`
[source,properties]
----
include::complete/src/main/resources/application.properties[]
----

In the same directory, create the `schema-hsqldb.sql` file and define the Customer table in it.

`src/main/resources/schema-hsqldb.sql`
[source,sql]
----
include::complete/src/main/resources/schema-hsqldb.sql[]
----

This table has the following properties:
 * The ID column will be automatically populated when a row is created. The initial value will be 1.
 * The combination of the FIRSTNAME and LASTNAME columns will construct a unique value.  This prevents duplicate records from being created.  For example, a record with the FIRSTNAME of 'Lisa' and the LASTNAME of 'Simpson' can only exist in the table once.

Next, in the same directory, create some initial data for our Customer table in the `data-hsqldb.sql` file:

`src/main/resources/data-hsqldb.sql`
[source,sql]
----
include::complete/src/main/resources/data-hsqldb.sql[]
----

== Create a Customer object
Now it's time to create the java code.  Create a Customer class with member variables of id, firstName and lastName.

`src/main/java/hello/Customer.java`
[source,java]
----
include::complete/src/main/java/hello/Customer.java[]
----

The `@NotNull` annotation is used to validate the firstName and lastName field values.

== Store and retrieve data

Next create a CustomerRepository class.  This class will contain the code for accessing the database.

`src/main/java/hello/CustomerRepository.java`
[source,java]
----
include::complete/src/main/java/hello/CustomerRepository.java[]
----

The `@Repository` annotation marks the class for auto-detection as part of the scanning process.  The `@Autowired` annotation indicates that Spring will automatically configure the JdbcTemplate parameter in the constructor.

The JdbcTemplate class provides the methods for using JDBC operations such as querying and updating. It also catches JDBC exceptions and translates them into more informative exceptions. The CustomerController you will create below will use these exceptions to provide granular error handling.

The first method uses the `queryForObject` method which expects only one row to be returned from the query.  The `?` variable tells JDBC to bind the variable which prevents SQL Injection attacks. The CustomerRowMapper constructs a Customer object out of the data returned in the `ResultSet` from the query. The CustomerRowMapper allows us to use the same mapping between the getCustomer(int id) and getCustomers() methods. The createCustomer(Customer customer) method inserts a new Customer record into the database using bind variables.  The id field is auto-generated by the database.  The new id is retrieved by capturing it with the `GeneratedKeyHolder`.

== Create a resource controller

Create a new controller for your Spring application:

`src/main/java/hello/CustomerController.java`
[source,java]
----
include::complete/src/main/java/hello/CustomerController.java[]
----

The `@RestController` marks the class for auto-detection as part of the scanning process.  It also indicates this class is a REST API and the methods will return JSON. The `@RequestMapping ("customers")` annotation maps the URL /customers to the entire class. Additional `@RequestMapping` annotations on the methods define sub mappings and accepted HTTP request methods.

Exceptions are handled by providing the `@ExceptionHandler` annotation on error methods.  For example, the `EmptyResultDataAccessException` is handled in the handleCustomerNotFoundException method. This situation occurs when the query in the CustomerRepository.getCustomer(int id) method could not find a record for the given id.  A 404 HTTP response code is returned by the handleCustomerNotFoundException method in this case.  The `DuplicateKeyException` is also handled using the `@ExceptionHandler` annotation and a 409 response is returned, indicating the customer already exists in the database.

== Make the application executable

Although it is possible to package this service as a traditional link:/understanding/WAR[WAR] file for deployment to an external application server, the simpler approach demonstrated below creates a standalone application. You package everything in a single, executable JAR file, driven by a good old Java `main()` method. Along the way, you use Spring's support for embedding the link:/understanding/Tomcat[Tomcat] servlet container as the HTTP runtime, instead of deploying to an external instance.


`src/main/java/hello/Application.java`
[source,java]
----
include::complete/src/main/java/hello/Application.java[]
----

The `main()` method defers to the {SpringApplication}[`SpringApplication`] helper class, providing `Application.class` as an argument to its `run()` method. This tells Spring to read the annotation metadata from `Application` and to manage it as a component in the link:/understanding/application-context[Spring application context].

The `@ComponentScan` annotation tells Spring to search recursively through the `hello` package and its children for classes marked directly or indirectly with Spring's {Component}[`@Component`] annotation. This directive ensures that Spring finds and registers the `CustomerController`, because it is marked with `@RestController`, which in turn is a kind of `@Component` annotation.

The {EnableAutoConfiguration}[`@EnableAutoConfiguration`] annotation switches on reasonable default behaviors based on the content of your classpath. For example, because the application depends on the embeddable version of Tomcat (tomcat-embed-core.jar), a Tomcat server is set up and configured with reasonable defaults on your behalf. And because the application also depends on Spring MVC (spring-webmvc.jar), a Spring MVC {DispatcherServlet}[`DispatcherServlet`] is configured and registered for you — no `web.xml` necessary! Auto-configuration is a powerful, flexible mechanism. See the {EnableAutoConfiguration}[API documentation] for further details.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_subhead.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]

:module: service
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/run_the_application_with_both.adoc[]

Logging output is displayed. The service should be up and running within a few seconds.


== Test the application

Now that the application is running, you can test it.

Get all customers:
....
$ curl -i http://localhost:8080/customers

[{"id":1,"firstName":"Fred","lastName":"Flintstone"},{"id":2,"firstName":"Wilma","lastName":"Flintstone"},{"id":3,"firstName":"Lisa","lastName":"Simpson"},{"id":4,"firstName":"Bart","lastName":"Simpson"},{"id":5,"firstName":"Maggie","lastName":"Simpson"}]
....

Create a customer:
....
$ curl -i -H "Content-Type:application/json" -d '{"lastName": "Simpson", "firstName":"Homer"}' http://localhost:8080/customers/customer

{"id":6,"firstName":"Homer","lastName":"Simpson"}
....

Get a specific customer:
....
$ curl -i http://localhost:8080/customers/customer/2

{"id":2,"firstName":"Wilma","lastName":"Flintstone"}
....


== Summary

Congratulations! You've just developed a Spring application using JdbcTemplate to access a database!



