:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-searching-elasticsearch
This guide walks you through the process of using https://spring.io/projects/spring-data-elasticsearch/[Spring Data Elasticsearch] to build an application that allows you to interact with Elasticsearch, a NoSQL distributed search engine.  

== What you'll build

You will store, search, and analyse `JSON` documents in Elasticsearch by using Spring Data Elasticsearch.

== What you'll need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/prereq_editor_jdk_buildtools.adoc[]

- An Elasticsearch server (See <<scratch>>)

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/how_to_complete_this_guide.adoc[]

[[scratch]]
== Setting up Elasticsearch Cluster

Before starting up, we need to have the Elasticsearch cluster up and running which ingests all our data and receives queries.

Elasticsearch is a free and open Distributed REST based search engine. It is a JSON based store, accepts queries via Elasticsearch specific QueryDSL OR Structured Query Language (SQL). It is freely available at elastic.co/downloads/elasticsearch, download it manually or  if you use a Mac, with Homebrew, by running the following command in a terminal window:

====
[source,bash]
----
brew tap elastic/tap
----
====

====
[source,bash]
----
brew install elastic/tap/elasticsearch-full
----
====

Once you unpack Redis, you can launch it with its default settings by running the following command:

====
[source,bash]
----
elasticsearch
----
====

You should see output similar to the following:

====
[source,text]
----
[o.e.n.Node] [mac.local] started
[INFO ][o.e.l.LicenseService] [mac.local] license [bdfa1fdb-bed5-4732-aac4-81010ac9b40b] mode [basic] - valid
----
====

Further to check the version and status of the Elasticsearch server, you can call below command with cURL. 

====
[source,bash]
----
curl http://localhost:9200
----
====

You should see output similar to the following:

====
[source,text]
----
{
  "name" : "Aravind-Putrevu.local",
  "cluster_name" : "elasticsearch_aravindputrevu",
  "cluster_uuid" : "VzGWAItpTV2dJN8tfKhKMg",
  "version" : {
    "number" : "7.12.1",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "3186837139b9c6b6d23c3200870651f10d3343b7",
    "build_date" : "2021-04-20T20:56:39.040728659Z",
    "build_snapshot" : false,
    "lucene_version" : "8.8.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
----
====

[[initial]]
=== Starting with Spring Initializer

If you use Maven, visit the https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.4.5.RELEASE&packaging=jar&jvmVersion=1.8&groupId=com.example&artifactId=indexing-data-elasticsearch&name=indexing-data-elasticsearch&description=Indexing%20data%20into%20Elasticsearch&packageName=com.example.elasticsearch&dependencies=data-elasticsearch,web[Spring Initializr] to generate a new project with the required dependency (Spring Data Elasticsearch).

The following listing shows the `pom.xml` file that is created when you choose Maven:


====
[src,xml]
----
include::complete/pom.xml[]
----
====

If you use Gradle, visit the https://start.spring.io/#!type=gradle-project&language=java&platformVersion=2.4.5.RELEASE&packaging=jar&jvmVersion=1.8&groupId=com.example&artifactId=indexing-data-elasticsearch&name=indexing-data-elasticsearch&description=Indexing%20data%20into%20Elasticsearch&packageName=com.example.elasticsearch&dependencies=data-elasticsearch,web[Spring Initializr] to generate a new project with the required dependency (Spring Data Elasticsearch).

The following listing shows the `build.gradle` file that is created when you choose Gradle:

====
[src,java]
----
include::complete/build.gradle[]
----
====

=== Manual Initialization (optional)

If you want to initialize the project manually rather than use the links shown earlier, follow the steps given below:

. Navigate to https://start.spring.io.
This service pulls in all the dependencies you need for an application and does most of the setup for you.
. Choose either Gradle or Maven and the language you want to use. This guide assumes that you chose Java.
. Click *Dependencies* and select *Spring Data Elasticsearch*.
. Click *Generate*.
. Download the resulting ZIP file, which is an archive of a web application that is configured with your choices.

NOTE: If your IDE has the Spring Initializr integration, you can complete this process from your IDE.

== Create an Entity

Elasticsearch stores data in Indices. In this guide, we will create an entity called `Account`. The following class shows the Account class (in `src/main/java/com/example/elasticsearch/entity/Account.java`)

====
[source,java,tabsize=2]
----
include::complete/src/main/java/com/example/elasticsearch/entity/Account.java[]
----
====

`@Document` annotation is applied at class level to declare that the mapping related information and index name of the Elasticsearch index. `VersionType` signifies the document version management. 

It is important to note, understand and change default values of some fields like `versionType`. Because, you might be overriding the best defaults of Elasticsearch, therefore you need to manage the feature by yourselves. 

`Account` class has several attributes like: `id`, `firstName`, and `lastName`, `age`, `gender` etc. Each document ingested into Elasticsearch has an `_id` field that uniquely identifies it, which is indexed so that documents can be looked up. 

`@Field` denoted the type of the field in the document. You can find all the accepted field types https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html[here].

NOTE: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html[Official documentation] has more information on different types of Mappings and few special fields. 


== Define a Elasticsearch Repository

Spring Data has the repository concept to manage the datastores. Spring Data Elasicsearch also has the implementation of ElasticsearchRepository.

To see how this works, create a repository interface that queries `AccountRepository` documents, as
the following listing (in
  `src/main/java/com/example/accessingdatamongodb/AccountRepository.java`) shows:

====
[source,java,tabsize=2]
----
include::complete/src/main/java/com/example/elasticsearch/AccountRepository.java[]
----
====

TKTK write advanced queries

The advantage of using Spring Data Elasticsearch to create a implementation of `ElasticsearchRepository` and add query methods with verbs like findBy. You don't need to create complete Elasticsearch implementation.

Now you can wire up this application and see what it looks like!

== Create an Application Class

Spring Initializr creates a application class. The following listing shows
the class (in
`src/main/java/com/example/elasticsearch/ElasticsearchApplication.java`):

====
[source,java,tabsize=2]
----
include::initial/src/main/java/com/example/elasticsearch/ElasticsearchApplication.java[]
----
====

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/spring-boot-application-new-path.adoc[]

Spring Boot automatically handles those repositories as long as they are included
in the same package (or a sub-package) of your `@SpringBootApplication` class. For more
control over the registration process, you can use the `@EnableElasticsearchRepositories`
annotation.

NOTE: By default, `@EnableElasticsearchRepositories` scans the current package for any interfaces
that extend one of Spring Data's repository interface. Alternatively, you can use `basePackageClasses=Repository.class` to instruct Spring Data Elasticsearch to scan a
different root package by type if your project layout has multiple projects and it does
not find your repositories.

TKTK - more about queries

Let's modify the simple class that the Spring Initializr created. Create some data and ingest it into Elasticsearch. The following listing shows the finished `ElasticsearchApplication` class (in
`src/main/java/com/example/elasticsearch/ElasticsearchApplication.java`):

====
[source,java,tabsize=2]
----
include::complete/src/main/java/com/example/elasticsearch/ElasticsearchApplication.java[]
----
====

`ElasticsearchApplication` includes a `main()` method which autowires `AccountRepository` class through which we access Elasticsearch which is running locally. Using Spring Data Elasticsearch methods `save()`, `findById()`, `count()`, we have created, queried `accounts` index in Elasticsearch. 

Note: If you have an `accounts` index in Elasticsearch, the application deleted all the documents using `deleteAll()` method.

Spring Data Elasticsearch uses the High level REST Client, using the `ElasticsearchRESTClientConfig`, we have configured the Elasticsearch instance.

Here is the listing which shows `ElasticsearchRESTClientConfig` class (in
`src/main/java/com/example/elasticsearch/ElasticsearchRESTClientConfig.java`):

====
[source,java,tabsize=2]
----
include::complete/src/main/java/com/example/elasticsearch/ElasticsearchRESTClientConfig.java[]
----
====

NOTE: For more information on Elasticsearch Clients and querying methods, you can refer to https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.clients[Spring Data Elasticsearch Documentation]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/build_an_executable_jar_mainhead.adoc[]
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/build_an_executable_jar_with_both.adoc[]

== Summary

Congratulations! You have created a Elasticsearch server and wrote a simple application that uses
Spring Data Elasticsearch to save objects, perform search, and even delete them, all without writing
a concrete repository implementation.

== See Also

The following guides may also be helpful:

* https://spring.io/guides/gs/accessing-data-jpa/[Accessing Data with JPA]
* https://spring.io/guides/gs/spring-boot/[Building Application with Spring Boot]
* https://spring.io/guides/gs/accessing-data-mysql/[Accessing data with MySQL]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/footer.adoc[]



