INSERT INTO CUSTOMERS (ID, FIRSTNAME, LASTNAME) VALUES (DEFAULT, 'Fred', 'Flintstone');
INSERT INTO CUSTOMERS (ID, FIRSTNAME, LASTNAME) VALUES (DEFAULT, 'Wilma', 'Flintstone');
INSERT INTO CUSTOMERS (ID, FIRSTNAME, LASTNAME) VALUES (DEFAULT, 'Lisa', 'Simpson');
INSERT INTO CUSTOMERS (ID, FIRSTNAME, LASTNAME) VALUES (DEFAULT, 'Bart', 'Simpson');
INSERT INTO CUSTOMERS (ID, FIRSTNAME, LASTNAME) VALUES (DEFAULT, 'Maggie', 'Simpson');
